### ISSUE TITLE
Table Config Errors

### ISSUE THREAD

**Issue by beardedtim** [kofile/react-a11y-table#17]
Give the following config:

```
export const defaultOpts = {
  cellOptions: {
    // add event listeners to all cells
    on: {},
  },
  headerOptions: {
    // add classname to all headers
    className: 'my-header',
    on: {},
  },
  rowOptions: {
    // add event listeners to all rows (minus header/footer rows)
    on: {},
    className: ({ isSelected, inCart, isViewed }) => ({
      'is-selected': isSelected,
      'in-cart': inCart,
      'is-viewed': isViewed,
    }),
  },
  data: [
    {
      cellOptions: {
        className: () => 'my cell',
        on: {},
      },
      headerOptions: {
        className: () => 'my cell',
        on: {},
      },
      rowOptions: {
        className: () => 'my cell',
        on: {},
      },
    },
    {
      cellOptions: {
        className: () => 'my cell',
        on: {},
      },
      headerOptions: {
        className: () => 'my cell',
        on: {},
      },
      rowOptions: {
        className: () => 'my cell',
        on: {},
      },
    },
  ],
};
```

And the following data:

```
[
        ['this', 'is not', 'working here', 'since mock server', 'and api', 'have already updated to v3'],
    ]
```

I get the following error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at http://localhost:5000/vendor.dll.js:102628:13
    at http://localhost:5000/vendor.dll.js:9155:45
    at http://localhost:5000/vendor.dll.js:101683:114
    at times (http://localhost:5000/vendor.dll.js:52620:17)
    at Object.f2 [as times] (http://localhost:5000/vendor.dll.js:425:16)
    at http://localhost:5000/vendor.dll.js:101676:11
    at args.(anonymous function) (http://localhost:5000/vendor.dll.js:101865:27)
    at _map (http://localhost:5000/vendor.dll.js:18780:19)
    at map (http://localhost:5000/vendor.dll.js:7746:14)
    at http://localhost:5000/vendor.dll.js:6210:15
```

Which points me to the error at the following line:

```
var value = R.compose(columnCellValueTransform || columnConfig.valueTransform, props.allValueTransform)(cellConfig);
```

**Comment by beardedtim** [comment]
user land error....
